main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

# for music web app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls', namespace='music')),
]

# If in developer mode, use this
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [

    # /music/
    path('', views.IndexView.as_view(), name='index'),

    # default html file name should be album_form (modelname_form)
    path('create-album/', views.CreateAlbumView.as_view(), name='create-album'),

    path('update-album/<int:pk>/', views.UpdateAlbumView.as_view(), name='update-album'),

    # /music/id/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('delete-album/<int:pk>/', views.DeleteAlbumView.as_view(), name='delete-album'),

    path('register/', views.SignupView.as_view(), name='register'),

    # /music/id/favorite/
    # path('<int:album_id>/favorite/', views.favorite, name='favorite'),
]

music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=100, null=False)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(null=True, blank=True)

    # for redirecting to detail page with primary key
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    # string representation
    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    # string representation
    def __str__(self):
        return self.song_title + ' - ' + self.album.artist

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User

        # specify available forms
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from . models import Album, Song
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.generic import View
from django.contrib.auth import authenticate, login
from .forms import UserForm

# where to redirect to after deletion
from django.urls import reverse_lazy

# old method using function based views
# def index(request):
#     albums = Album.objects.all()
#     context = {'albums': albums, }
#     return render(request, 'music/index.html', context)
#
#
# def detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     context = {'album': album}
#     return render(request, 'music/detail.html', context)
#
#
# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except(KeyError, Song.DoesNotExist):
#         context = {
#             'album': album,
#             'error_message': 'You did not select any song',
#         }
#         return render(request, 'music/detail.html', context)
#     else:
#         if selected_song.is_favorite:
#             selected_song.is_favorite = False
#             selected_song.save()
#         else:
#             selected_song.is_favorite = True
#             selected_song.save()
#
#         context = {
#             'album': album
#         }
#         return render(request, 'music/detail.html', context)


# new method using class based views
class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'albums'

    # use function to get model / database
    # default name in index page will be album list
    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DeleteView):
    model = Album
    template_name = 'music/detail.html'


class CreateAlbumView(generic.CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class UpdateAlbumView(generic.UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class DeleteAlbumView(generic.DeleteView):
    model = Album

    # redirect to homepage after deletion
    success_url = reverse_lazy('music:index')


class SignupView(View):
    form_class = UserForm
    template_name = 'music/signup_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}
    Create Album
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-8">

                <form class="form-control" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'music/form_template.html' %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>

{% endblock %}

music/templates/music/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <!--The two jquery cdn must be on top of the bootstrap-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>{% block title %} {% endblock %}Music Website</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">Music</a>

    <!--responsive navbar-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:index' %}">Album</a>
          <span class="glyphicon glyphicon-calendar"></span>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:index' %}">Songs</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:create-album' %}">Add Album</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:index' %}">Logout</a>
      </li>

    </ul>

    <form class="form-inline my-2 my-lg-0" role="search" method="get" action="#">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </div>

</nav>

    {% block content %}

    {% endblock %}

</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}
    {{ album.album_title }}
{% endblock %}

{% block content %}

    {% if album %}
        <h3>Details of this album are:</h3>
{#        {% if album.album_logo %}#}
{#            <img src="{{ album.album_logo.url }}" class="img-responsive" width="150"/>#}
{#        {% endif %}#}

        <img src="{{ album.album_logo.url }}" class="img-responsive" width="100"/>
        <p><strong>Artist:</strong> {{ album.artist }}</p>
        <p><strong>Title:</strong> {{ album.album_title }}</p>
    {% endif %}

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block title %}
    Music
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <h3>Music</h3>
    {% if albums %}
    <ul>
        {% for album in albums %}
            {% if album.album_logo %}
            <img src="{{ album.album_logo.url }}" class="img-responsive" width="100"/>
            {% endif %}
            <li><a href="{% url 'music:detail' album.id %}">
                {{ album.album_title }}</a>
            </li>

            <form method="post" action="{% url 'music:delete-album' album.id %}" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}">
                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            </form>

            <a href="{% url 'music:update-album' album.id %}"><button class="btn btn-sm btn-warning">Update</button></a>
        {% endfor %}
    </ul>
    {% else %}
        <h5>No albums Available</h5>
    {% endif %}

    </div>

{% endblock %}

music/templates/music/signup_form.html
{% extends 'music/base.html' %}
{% load static %}

{% block title %}
    Signup page
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-8">

                <form class="form-control" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'music/form_template.html' %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>

{% endblock %}